// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDupVh4a_BioIJteaPBRZKgBFBGhhDKY8Q',
    appId: '1:181782604750:web:38e50f7318addefa5c199f',
    messagingSenderId: '181782604750',
    projectId: 'elevate-fcai-cu',
    authDomain: 'elevate-fcai-cu.firebaseapp.com',
    databaseURL: 'https://elevate-fcai-cu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elevate-fcai-cu.firebasestorage.app',
    measurementId: 'G-4QHYJPPGK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoVW1X9LBfa7Gna_9DfYT73a0BckbKaXs',
    appId: '1:181782604750:android:84bb01fe9d110bc85c199f',
    messagingSenderId: '181782604750',
    projectId: 'elevate-fcai-cu',
    databaseURL: 'https://elevate-fcai-cu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elevate-fcai-cu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdL9F3_XqiS12ZWBPdc3nF_Jcv2IgOk0',
    appId: '1:181782604750:ios:f460b9a567dbecf85c199f',
    messagingSenderId: '181782604750',
    projectId: 'elevate-fcai-cu',
    databaseURL: 'https://elevate-fcai-cu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elevate-fcai-cu.firebasestorage.app',
    androidClientId: '181782604750-e8ujlt8gllq1tvcrbdf6naj4slr0pk0p.apps.googleusercontent.com',
    iosClientId: '181782604750-deobad838siu3bnn56hbsjk64chiqhfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.elevate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdL9F3_XqiS12ZWBPdc3nF_Jcv2IgOk0',
    appId: '1:181782604750:ios:f460b9a567dbecf85c199f',
    messagingSenderId: '181782604750',
    projectId: 'elevate-fcai-cu',
    databaseURL: 'https://elevate-fcai-cu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elevate-fcai-cu.firebasestorage.app',
    androidClientId: '181782604750-e8ujlt8gllq1tvcrbdf6naj4slr0pk0p.apps.googleusercontent.com',
    iosClientId: '181782604750-deobad838siu3bnn56hbsjk64chiqhfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.elevate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDupVh4a_BioIJteaPBRZKgBFBGhhDKY8Q',
    appId: '1:181782604750:web:7ad94d693331e82e5c199f',
    messagingSenderId: '181782604750',
    projectId: 'elevate-fcai-cu',
    authDomain: 'elevate-fcai-cu.firebaseapp.com',
    databaseURL: 'https://elevate-fcai-cu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elevate-fcai-cu.firebasestorage.app',
    measurementId: 'G-W8HZJT2NE7',
  );
}
